# Basic Tensor Operations

Basic tensor operations using TensorFlow v2.

In [1]:
from __future__ import print_function
import tensorflow as tf

In [2]:
# Define tensor constants.
a = tf.constant(4)
b = tf.constant(3)
c = tf.constant(5)

In [3]:
# Various tensor operations.
# Note: Tensors also support python operators (+, *, ...)
add = tf.add(a, b)
sub = tf.subtract(a, b)
mul = tf.multiply(a, b)
div = tf.divide(a, b)

# Access tensors value.
print("add =", add.numpy())
print("sub =", sub.numpy())
print("mul =", mul.numpy())
print("div =", div.numpy())

add = 7
sub = 1
mul = 12
div = 1.3333333333333333


In [4]:
# Some more operations.
mean = tf.reduce_mean([a, b, c])
sum = tf.reduce_sum([a, b, c])

# Access tensors value.
print("mean =", mean.numpy())
print("sum =", sum.numpy())

mean = 4
sum = 12


In [5]:
# Matrix multiplications.
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[5., 6.], [7., 8.]])

product = tf.matmul(matrix1, matrix2)

In [6]:
# Display Tensor.
product

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[19., 22.],
       [43., 50.]], dtype=float32)>

In [7]:
# Convert Tensor to Numpy.
product.numpy()

array([[19., 22.],
       [43., 50.]], dtype=float32)

In [8]:
rank=tf.linalg.matrix_rank(matrix1)

In [9]:
# Convert Tensor to Numpy.
rank.numpy()

2

In [10]:
adj=tf.linalg.adjoint(matrix1)

In [11]:
adj.numpy()

array([[1., 3.],
       [2., 4.]], dtype=float32)

In [12]:
matrix3 = tf.constant([[1., 2.,4.], [3., 4.,5.],[7.,8.,9.]])

In [13]:
#  Upper triangular part.
UpperMat=tf.linalg.band_part(matrix3, 0, -1)

In [14]:
UpperMat.numpy()

array([[1., 2., 4.],
       [0., 4., 5.],
       [0., 0., 9.]], dtype=float32)

In [15]:
# Lower triangular part.
LowerMat=tf.linalg.band_part(matrix3,-1, 0)

In [16]:
LowerMat.numpy()

array([[1., 0., 0.],
       [3., 4., 0.],
       [7., 8., 9.]], dtype=float32)

In [17]:
# Diagonal.
DiagonalMat=tf.linalg.band_part(matrix3,0, 0)

In [18]:
DiagonalMat.numpy()

array([[1., 0., 0.],
       [0., 4., 0.],
       [0., 0., 9.]], dtype=float32)